steps:

  lint:
    image: python:3.14-slim
    commands:
      - pip install --upgrade pip
      - pip install -e .[lint]

      - ruff check ./src --output-format=github
      - ruff format --check ./src

      - mypy ./src --install-types --non-interactive --check-untyped-defs
    when:
      - event: push
        branch: main
      - event: pull_request
      - event: tag

  test:
    image: python:3.14-slim
    commands:
      - pip install --upgrade pip
      - pip install -e .[test]
      - pytest --cov-fail-under=100
    when:
      - event: push
        branch: main
      - event: pull_request
      - event: tag

  publish:
    image: python:3.14-slim
    depends_on: [lint, test]
    environment:
      PYPI_TOKEN:
        from_secret: pypi_token
    commands:
      - pip install --upgrade pip
      - pip install build twine
      - python -m build
      - twine upload --non-interactive --username __token__ --password $PYPI_TOKEN --skip-existing dist/*
    when:
      - event: tag
