"""Tests for src/datorum/binding/settings.py."""

from datorum.binding.settings import ContextBindType


def test_context_bind_type_flags():
    assert not ContextBindType.model.is_domain()
    assert ContextBindType.model.is_input()
    assert ContextBindType.model.is_output()
    assert ContextBindType.model.is_model()
    assert not ContextBindType.model.is_text()
    assert not ContextBindType.model.is_bytes()
    assert not ContextBindType.model.is_path()
    assert not ContextBindType.model.is_metadata()
    assert ContextBindType.model.is_io()

    assert not ContextBindType.model_input.is_domain()
    assert ContextBindType.model_input.is_input()
    assert not ContextBindType.model_input.is_output()
    assert ContextBindType.model_input.is_model()
    assert not ContextBindType.model_input.is_text()
    assert not ContextBindType.model_input.is_bytes()
    assert not ContextBindType.model_input.is_path()
    assert not ContextBindType.model_input.is_metadata()
    assert ContextBindType.model_input.is_io()

    assert not ContextBindType.model_output.is_domain()
    assert not ContextBindType.model_output.is_input()
    assert ContextBindType.model_output.is_output()
    assert ContextBindType.model_output.is_model()
    assert not ContextBindType.model_output.is_text()
    assert not ContextBindType.model_output.is_bytes()
    assert not ContextBindType.model_output.is_path()
    assert not ContextBindType.model_output.is_metadata()
    assert ContextBindType.model_output.is_io()

    assert not ContextBindType.text.is_domain()
    assert ContextBindType.text.is_input()
    assert ContextBindType.text.is_output()
    assert not ContextBindType.text.is_model()
    assert ContextBindType.text.is_text()
    assert not ContextBindType.text.is_bytes()
    assert not ContextBindType.text.is_path()
    assert not ContextBindType.text.is_metadata()
    assert ContextBindType.text.is_io()

    assert not ContextBindType.text_input.is_domain()
    assert ContextBindType.text_input.is_input()
    assert not ContextBindType.text_input.is_output()
    assert not ContextBindType.text_input.is_model()
    assert ContextBindType.text_input.is_text()
    assert not ContextBindType.text_input.is_bytes()
    assert not ContextBindType.text_input.is_path()
    assert not ContextBindType.text_input.is_metadata()
    assert ContextBindType.text_input.is_io()

    assert not ContextBindType.text_output.is_domain()
    assert not ContextBindType.text_output.is_input()
    assert ContextBindType.text_output.is_output()
    assert not ContextBindType.text_output.is_model()
    assert ContextBindType.text_output.is_text()
    assert not ContextBindType.text_output.is_bytes()
    assert not ContextBindType.text_output.is_path()
    assert not ContextBindType.text_output.is_metadata()
    assert ContextBindType.text_output.is_io()

    assert not ContextBindType.bytes.is_domain()
    assert ContextBindType.bytes.is_input()
    assert ContextBindType.bytes.is_output()
    assert not ContextBindType.bytes.is_model()
    assert not ContextBindType.bytes.is_text()
    assert ContextBindType.bytes.is_bytes()
    assert not ContextBindType.bytes.is_path()
    assert not ContextBindType.bytes.is_metadata()
    assert ContextBindType.bytes.is_io()

    assert not ContextBindType.bytes_input.is_domain()
    assert ContextBindType.bytes_input.is_input()
    assert not ContextBindType.bytes_input.is_output()
    assert not ContextBindType.bytes_input.is_model()
    assert not ContextBindType.bytes_input.is_text()
    assert ContextBindType.bytes_input.is_bytes()
    assert not ContextBindType.bytes_input.is_path()
    assert not ContextBindType.bytes_input.is_metadata()
    assert ContextBindType.bytes_input.is_io()

    assert not ContextBindType.bytes_output.is_domain()
    assert not ContextBindType.bytes_output.is_input()
    assert ContextBindType.bytes_output.is_output()
    assert not ContextBindType.bytes_output.is_model()
    assert not ContextBindType.bytes_output.is_text()
    assert ContextBindType.bytes_output.is_bytes()
    assert not ContextBindType.bytes_output.is_path()
    assert not ContextBindType.bytes_output.is_metadata()
    assert ContextBindType.bytes_output.is_io()

    assert not ContextBindType.document_path.is_domain()
    assert ContextBindType.document_path.is_input()
    assert not ContextBindType.document_path.is_output()
    assert not ContextBindType.document_path.is_model()
    assert not ContextBindType.document_path.is_text()
    assert not ContextBindType.document_path.is_bytes()
    assert ContextBindType.document_path.is_path()
    assert not ContextBindType.document_path.is_metadata()
    assert not ContextBindType.document_path.is_io()

    assert not ContextBindType.document_metadata.is_domain()
    assert ContextBindType.document_metadata.is_input()
    assert ContextBindType.document_metadata.is_output()
    assert not ContextBindType.document_metadata.is_model()
    assert not ContextBindType.document_metadata.is_text()
    assert not ContextBindType.document_metadata.is_bytes()
    assert not ContextBindType.document_metadata.is_path()
    assert ContextBindType.document_metadata.is_metadata()
    assert not ContextBindType.document_metadata.is_io()

    assert ContextBindType.domain_path.is_domain()
    assert ContextBindType.domain_path.is_input()
    assert not ContextBindType.domain_path.is_output()
    assert not ContextBindType.domain_path.is_model()
    assert not ContextBindType.domain_path.is_text()
    assert not ContextBindType.domain_path.is_bytes()
    assert ContextBindType.domain_path.is_path()
    assert not ContextBindType.domain_path.is_metadata()
    assert not ContextBindType.domain_path.is_io()

    assert ContextBindType.domain_metadata.is_domain()
    assert ContextBindType.domain_metadata.is_input()
    assert ContextBindType.domain_metadata.is_output()
    assert not ContextBindType.domain_metadata.is_model()
    assert not ContextBindType.domain_metadata.is_text()
    assert not ContextBindType.domain_metadata.is_bytes()
    assert not ContextBindType.domain_metadata.is_path()
    assert ContextBindType.domain_metadata.is_metadata()
    assert not ContextBindType.domain_metadata.is_io()