from ..core.exceptions import DatorumBaseError, RegistryError


class CredentialError(DatorumBaseError): ...


class KeyNotFoundError(CredentialError): ...


class InvalidKeyNameError(CredentialError): ...


class ResourceFactoryError(RegistryError): ...


class BinderError(DatorumBaseError): ...


class ResourceBindingError(BinderError): ...


class ContextBindingError(BinderError): ...
