class DatorumBaseError(Exception): ...


class SettingsError(DatorumBaseError): ...


class RegistryError(DatorumBaseError): ...


class SecurityBackendError(DatorumBaseError): ...


# MODEL


class DatorumModelException(DatorumBaseError): ...


class ConfigException(DatorumModelException): ...


class NoFilePathException(DatorumModelException): ...


class DocumentNotFoundException(DatorumModelException): ...


class DocumentNotLoadedException(DatorumModelException): ...


class UnknownDataModelException(DatorumModelException): ...


class DocumentFormatException(DatorumModelException): ...


class OrphanSourceException(DatorumModelException): ...


class InvalidIdentifierException(DatorumModelException): ...


class KeyStoreException(DatorumModelException): ...


class ToolBoxException(DatorumModelException): ...


# WORKER


class DatorumWorkerException(DatorumBaseError): ...


class PauseRequested(DatorumWorkerException): ...


class InvalidJobException(DatorumWorkerException): ...


class InvalidJobTypeException(DatorumWorkerException): ...


class JobFailedException(DatorumWorkerException): ...


class MissingContextException(DatorumWorkerException): ...


class InvalidContextBindException(DatorumWorkerException): ...


class InvalidResourceBindException(DatorumWorkerException): ...


class InvalidResourceException(DatorumWorkerException): ...


class UserSessionException(DatorumWorkerException): ...


class AgentWorkerException(DatorumWorkerException): ...


class ToolWorkerException(DatorumWorkerException): ...


class DecisionWorkerException(DatorumWorkerException): ...


class PipelineWorkerException(DatorumWorkerException): ...


class OrchestratorException(DatorumWorkerException): ...

