from ..core.exceptions import DatorumBaseError, SettingsError, RegistryError


class DocumentTypeError(RegistryError): ...

class DocumentModelError(RegistryError): ...

class DocumentHandlerError(RegistryError): ...

class ResourceFactoryError(RegistryError): ...


class DocumentReferenceError(SettingsError): ...

class DocumentReadingError(DocumentReferenceError): ...

class DocumentWritingError(DocumentReferenceError): ...


class BinderError(DatorumBaseError): ...

class ResourceBindingError(BinderError): ...

class ContextBindingError(BinderError): ...