from ..core.exceptions import SettingsError, RegistryError


class DocumentTypeError(RegistryError): ...

class DocumentModelError(RegistryError): ...

class DocumentHandlerError(RegistryError): ...


class DocumentReferenceError(RegistryError): ...

class DocumentReadingError(DocumentReferenceError): ...

class DocumentWritingError(DocumentReferenceError): ...

