class DatorumException(Exception): ...


class OrphanSourceException(DatorumException): ...


class InvalidIdentifierException(DatorumException): ...


class InferenceException(DatorumException): ...


class ScraperException(DatorumException): ...


class ChunkerException(DatorumException): ...
