class DatorumException(Exception): ...


# MODEL


class DatorumModelException(DatorumException): ...


class ConfigException(DatorumModelException): ...


class NoFilePathException(DatorumModelException): ...


class DocumentNotFoundException(DatorumModelException): ...


class DocumentNotLoadedException(DatorumModelException): ...


class UnknownDataModelException(DatorumModelException): ...


class DocumentFormatException(DatorumModelException): ...


class OrphanSourceException(DatorumModelException): ...


class InvalidIdentifierException(DatorumModelException): ...


class KeyStoreException(DatorumModelException): ...


class ToolBoxException(DatorumModelException): ...


# SERVICE


class DatorumServiceException(DatorumException): ...


class InferenceException(DatorumServiceException): ...


class ScraperException(DatorumServiceException): ...


class ChunkerException(DatorumServiceException): ...
