from ..core.exceptions import DatorumBaseError


class JobError(DatorumBaseError): ...


class JobStatusError(JobError): ...


class WorkerError(DatorumBaseError): ...


class WorkerStartUpError(WorkerError): ...
